services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-agendai
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendai
      MYSQL_USER: agendai
      MYSQL_PASSWORD: agendai#password

    ports:
      - '3306:3306'
