version: '3.9'

services:
  mysql-dev:
    image: mysql:latest
    ports:
      - '3306:3306'
    container_name: mysql-agendai
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendai
      MYSQL_USER: agendai
      MYSQL_PASSWORD: agendai#password
    restart: unless-stopped
    networks:
      - agendai-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    container_name: redis-agendai
    restart: unless-stopped
    networks:
      - agendai-network

networks:
  agendai-network:
    driver: bridge
